#define _FABM_DIMENSION_COUNT_ 2
#define _FABM_DEPTH_DIMENSION_INDEX_ 2
#define _FABM_VECTORIZED_DIMENSION_INDEX_ 1

#define _FABM_MASK_TYPE_ integer
#define _FABM_UNMASKED_VALUE_ 1
#define _FABM_HORIZONTAL_MASK_

#include "fabm.h"

