#!/bin/bash

set -e

REPO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

WORK_DIR=`mktemp -d`
cd ${WORK_DIR}
cmake ${REPO_DIR}/extern/fabm/src/drivers/python
make install
cd -
rm -rf ${WORK_DIR}
