/* This include file is automatically generated by Cython for 'public' functions. */
#include "fabm_base.h"

#ifdef __cplusplus
extern "C" {
#endif

   int prepend_cwd_to_path() {
      PyObject* psys;
      PyObject* sys_path;
      PyObject* empty_string;
      int iret;

      psys = PyImport_ImportModule("sys");
      if (psys == NULL) return (1);
      sys_path = PyObject_GetAttrString(psys, "path");
      Py_DECREF(psys);
      if (sys_path == NULL) return (1);
      empty_string = PyUnicode_FromString("");
      iret = PyList_Insert(sys_path, 0, empty_string);
      Py_DECREF(sys_path);
      Py_DECREF(empty_string);
      return (iret);
   }

   int embedded_python_initialize(const char* program_name, const char* home)
   {
      if (Py_IsInitialized() != 0) {
         fputs("Error: Python already initialized\n", stderr);
         return(1);
      }

      PyStatus status;

      PyConfig config;
      PyConfig_InitPythonConfig(&config);

      status = PyConfig_SetBytesString(&config, &config.program_name, program_name);
      if (PyStatus_Exception(status)) goto error;

      status = PyConfig_SetBytesString(&config, &config.home, home);
      if (PyStatus_Exception(status)) goto error;

      config.install_signal_handlers = 0; /* Disable signal handlers */

      /* Add a built-in module, before Py_Initialize */
      if (PyImport_AppendInittab("fabm_base", PyInit_fabm_base) == -1) {
         fputs("Error: could not extend in-built modules table\n", stderr);
         goto error;
      }

      /* Initialize the Python interpreter.  Required.
         If this step fails, it will be a fatal error. */
      status = Py_InitializeFromConfig(&config);
      if (PyStatus_Exception(status)) goto error;

      PyConfig_Clear(&config);

      if (prepend_cwd_to_path() != 0) {
         PyErr_Print();
         return(1);
      }

      return(0);
   error:
      if (PyStatus_Exception(status)) fputs(status.err_msg, stderr);
      PyConfig_Clear(&config);
      return(1);
   }

   PyObject* embedded_python_get_model(const char* module_name, const char* class_name, void* base) {
      PyObject* pmodule;
      PyObject* pclass;
      PyObject* presult;

      pmodule = PyImport_ImportModule(module_name);
      if (pmodule == NULL)  goto error;
      pclass = PyObject_GetAttrString(pmodule, class_name);
      Py_DECREF(pmodule);
      if (pclass == NULL) goto error;
      pnext_base = base;
      presult = PyObject_CallNoArgs(pclass);
      Py_DECREF(pclass);
      if (presult == NULL) goto error;
      return(presult);

   error:
      PyErr_Print();
      return(NULL);
   }

#ifdef __cplusplus
}
#endif