#define _FABM_DIMENSION_COUNT_ 3
#define _FABM_DEPTH_DIMENSION_INDEX_ 3
#define _FABM_VECTORIZED_DIMENSION_INDEX_ 1

#define _FABM_MASK_TYPE_ real(8)
#define _FABM_UNMASKED_VALUE_ 1.
#define _FABM_HORIZONTAL_MASK_
#define _FABM_VERTICAL_BOTTOM_TO_SURFACE_

#include "fabm.h"


