! DO NOT EDIT THIS FILE.
! It is automatically generated by ..\util\standard_variables\parse_standard_variables.py from ..\util\standard_variables\variables.yaml.
! Edit variables.yaml instead and re-run parse_standard_variables.py.
! Interior variables
type (type_interior_standard_variable) :: alkalinity_expressed_as_mole_equivalent
type (type_interior_standard_variable) :: attenuation_coefficient_of_photosynthetic_radiative_flux
type (type_interior_standard_variable) :: attenuation_coefficient_of_shortwave_flux
type (type_interior_standard_variable) :: cell_thickness
type (type_interior_standard_variable) :: density
type (type_interior_standard_variable) :: depth
type (type_interior_standard_variable) :: downwelling_photosynthetic_radiative_flux
type (type_interior_standard_variable) :: downwelling_shortwave_flux
type (type_interior_standard_variable) :: fractional_saturation_of_oxygen
type (type_interior_standard_variable) :: mass_concentration_of_suspended_matter
type (type_interior_standard_variable) :: mole_concentration_of_ammonium
type (type_interior_standard_variable) :: mole_concentration_of_carbonate_expressed_as_carbon
type (type_interior_standard_variable) :: mole_concentration_of_dissolved_inorganic_carbon
type (type_interior_standard_variable) :: mole_concentration_of_dissolved_iron
type (type_interior_standard_variable) :: mole_concentration_of_nitrate
type (type_interior_standard_variable) :: mole_concentration_of_phosphate
type (type_interior_standard_variable) :: mole_concentration_of_silicate
type (type_interior_standard_variable) :: net_rate_of_absorption_of_shortwave_energy_in_layer
type (type_interior_standard_variable) :: ph_reported_on_total_scale
type (type_interior_standard_variable) :: practical_salinity
type (type_interior_standard_variable) :: pressure
type (type_interior_standard_variable) :: secchi_depth
type (type_interior_standard_variable) :: temperature

! Bottom variables
type (type_bottom_standard_variable) :: bottom_depth
type (type_bottom_standard_variable) :: bottom_depth_below_geoid
type (type_bottom_standard_variable) :: bottom_roughness_length
type (type_bottom_standard_variable) :: bottom_stress

! Surface variables
type (type_surface_standard_variable) :: cloud_area_fraction
type (type_surface_standard_variable) :: ice_area_fraction
type (type_surface_standard_variable) :: mole_fraction_of_carbon_dioxide_in_air
type (type_surface_standard_variable) :: surface_air_pressure
type (type_surface_standard_variable) :: surface_albedo
type (type_surface_standard_variable) :: surface_downwelling_photosynthetic_radiative_flux
type (type_surface_standard_variable) :: surface_downwelling_photosynthetic_radiative_flux_in_air
type (type_surface_standard_variable) :: surface_downwelling_shortwave_flux
type (type_surface_standard_variable) :: surface_downwelling_shortwave_flux_in_air
type (type_surface_standard_variable) :: surface_drag_coefficient_in_air
type (type_surface_standard_variable) :: surface_specific_humidity
type (type_surface_standard_variable) :: surface_temperature
type (type_surface_standard_variable) :: wind_speed

! Horizontal variables
type (type_horizontal_standard_variable) :: latitude
type (type_horizontal_standard_variable) :: longitude

! Global variables
type (type_global_standard_variable) :: number_of_days_since_start_of_the_year

! Universal variables
type (type_universal_standard_variable) :: total_carbon
type (type_universal_standard_variable) :: total_iron
type (type_universal_standard_variable) :: total_nitrogen
type (type_universal_standard_variable) :: total_phosphorus
type (type_universal_standard_variable) :: total_silicate

