! DO NOT EDIT THIS FILE.
! It is automatically generated by ../util/standard_variables/parse_standard_variables.py from ../util/standard_variables/variables.yaml.
! Edit variables.yaml instead and re-run parse_standard_variables.py.
self%alkalinity_expressed_as_mole_equivalent%name = 'alkalinity_expressed_as_mole_equivalent'
self%alkalinity_expressed_as_mole_equivalent%units = 'mmol m-3'
self%alkalinity_expressed_as_mole_equivalent%cf_names = 'sea_water_alkalinity_expressed_as_mole_equivalent'
call add(self%alkalinity_expressed_as_mole_equivalent)

self%attenuation_coefficient_of_photosynthetic_radiative_flux%name = 'attenuation_coefficient_of_photosynthetic_radiative_flux'
self%attenuation_coefficient_of_photosynthetic_radiative_flux%units = 'm-1'
self%attenuation_coefficient_of_photosynthetic_radiative_flux%aggregate_variable = .true.
call add(self%attenuation_coefficient_of_photosynthetic_radiative_flux)

self%attenuation_coefficient_of_shortwave_flux%name = 'attenuation_coefficient_of_shortwave_flux'
self%attenuation_coefficient_of_shortwave_flux%units = 'm-1'
self%attenuation_coefficient_of_shortwave_flux%aggregate_variable = .true.
call add(self%attenuation_coefficient_of_shortwave_flux)

self%cell_thickness%name = 'cell_thickness'
self%cell_thickness%units = 'm'
self%cell_thickness%cf_names = 'cell_thickness'
call add(self%cell_thickness)

self%density%name = 'density'
self%density%units = 'kg m-3'
self%density%cf_names = 'sea_water_density'
call add(self%density)

self%depth%name = 'depth'
self%depth%units = 'm'
self%depth%cf_names = 'depth'
call add(self%depth)

self%downwelling_photosynthetic_radiative_flux%name = 'downwelling_photosynthetic_radiative_flux'
self%downwelling_photosynthetic_radiative_flux%units = 'W m-2'
self%downwelling_photosynthetic_radiative_flux%cf_names = 'downwelling_photosynthetic_radiative_flux_in_sea_water'
call add(self%downwelling_photosynthetic_radiative_flux)

self%downwelling_shortwave_flux%name = 'downwelling_shortwave_flux'
self%downwelling_shortwave_flux%units = 'W m-2'
self%downwelling_shortwave_flux%cf_names = 'downwelling_shortwave_flux_in_sea_water'
call add(self%downwelling_shortwave_flux)

self%fractional_saturation_of_oxygen%name = 'fractional_saturation_of_oxygen'
self%fractional_saturation_of_oxygen%units = '1'
self%fractional_saturation_of_oxygen%cf_names = 'fractional_saturation_of_oxygen_in_sea_water'
call add(self%fractional_saturation_of_oxygen)

self%mass_concentration_of_suspended_matter%name = 'mass_concentration_of_suspended_matter'
self%mass_concentration_of_suspended_matter%units = 'g m-3'
self%mass_concentration_of_suspended_matter%cf_names = 'mass_concentration_of_suspended_matter_in_sea_water,concentration_of_suspended_matter_in_sea_water'
call add(self%mass_concentration_of_suspended_matter)

self%mole_concentration_of_ammonium%name = 'mole_concentration_of_ammonium'
self%mole_concentration_of_ammonium%units = 'mmol m-3'
self%mole_concentration_of_ammonium%cf_names = 'mole_concentration_of_ammonium_in_sea_water'
call add(self%mole_concentration_of_ammonium)

self%mole_concentration_of_carbonate_expressed_as_carbon%name = 'mole_concentration_of_carbonate_expressed_as_carbon'
self%mole_concentration_of_carbonate_expressed_as_carbon%units = 'mmol m-3'
self%mole_concentration_of_carbonate_expressed_as_carbon%cf_names = 'mole_concentration_of_carbonate_expressed_as_carbon_in_sea_water'
call add(self%mole_concentration_of_carbonate_expressed_as_carbon)

self%mole_concentration_of_dissolved_inorganic_carbon%name = 'mole_concentration_of_dissolved_inorganic_carbon'
self%mole_concentration_of_dissolved_inorganic_carbon%units = 'mmol m-3'
self%mole_concentration_of_dissolved_inorganic_carbon%cf_names = 'mole_concentration_of_dissolved_inorganic_carbon_in_sea_water'
call add(self%mole_concentration_of_dissolved_inorganic_carbon)

self%mole_concentration_of_dissolved_iron%name = 'mole_concentration_of_dissolved_iron'
self%mole_concentration_of_dissolved_iron%units = 'umol m-3'
self%mole_concentration_of_dissolved_iron%cf_names = 'mole_concentration_of_dissolved_iron_in_sea_water'
call add(self%mole_concentration_of_dissolved_iron)

self%mole_concentration_of_nitrate%name = 'mole_concentration_of_nitrate'
self%mole_concentration_of_nitrate%units = 'mmol m-3'
self%mole_concentration_of_nitrate%cf_names = 'mole_concentration_of_nitrate_in_sea_water'
call add(self%mole_concentration_of_nitrate)

self%mole_concentration_of_phosphate%name = 'mole_concentration_of_phosphate'
self%mole_concentration_of_phosphate%units = 'mmol m-3'
self%mole_concentration_of_phosphate%cf_names = 'mole_concentration_of_phosphate_in_sea_water'
call add(self%mole_concentration_of_phosphate)

self%mole_concentration_of_silicate%name = 'mole_concentration_of_silicate'
self%mole_concentration_of_silicate%units = 'mmol m-3'
self%mole_concentration_of_silicate%cf_names = 'mole_concentration_of_silicate_in_sea_water'
call add(self%mole_concentration_of_silicate)

self%net_rate_of_absorption_of_shortwave_energy_in_layer%name = 'net_rate_of_absorption_of_shortwave_energy_in_layer'
self%net_rate_of_absorption_of_shortwave_energy_in_layer%units = 'W m-2'
self%net_rate_of_absorption_of_shortwave_energy_in_layer%cf_names = 'net_rate_of_absorption_of_shortwave_energy_in_ocean_layer'
call add(self%net_rate_of_absorption_of_shortwave_energy_in_layer)

self%ph_reported_on_total_scale%name = 'ph_reported_on_total_scale'
self%ph_reported_on_total_scale%units = '1'
self%ph_reported_on_total_scale%cf_names = 'sea_water_ph_reported_on_total_scale'
call add(self%ph_reported_on_total_scale)

self%practical_salinity%name = 'practical_salinity'
self%practical_salinity%units = '1e-3'
self%practical_salinity%cf_names = 'sea_water_practical_salinity'
call add(self%practical_salinity)

self%pressure%name = 'pressure'
self%pressure%units = 'dbar'
self%pressure%cf_names = 'sea_water_pressure'
call add(self%pressure)

self%secchi_depth%name = 'secchi_depth'
self%secchi_depth%units = 'm'
self%secchi_depth%cf_names = 'secchi_depth_of_sea_water'
call add(self%secchi_depth)

self%temperature%name = 'temperature'
self%temperature%units = 'degree_Celsius'
self%temperature%cf_names = 'sea_water_temperature'
call add(self%temperature)

self%bottom_depth%name = 'bottom_depth'
self%bottom_depth%units = 'm'
call add(self%bottom_depth)

self%bottom_depth_below_geoid%name = 'bottom_depth_below_geoid'
self%bottom_depth_below_geoid%units = 'm'
self%bottom_depth_below_geoid%cf_names = 'sea_floor_depth_below_geoid,sea_floor_depth'
call add(self%bottom_depth_below_geoid)

self%bottom_roughness_length%name = 'bottom_roughness_length'
self%bottom_roughness_length%units = 'm'
call add(self%bottom_roughness_length)

self%bottom_stress%name = 'bottom_stress'
self%bottom_stress%units = 'Pa'
call add(self%bottom_stress)

self%cloud_area_fraction%name = 'cloud_area_fraction'
self%cloud_area_fraction%units = '1'
self%cloud_area_fraction%cf_names = 'cloud_area_fraction'
call add(self%cloud_area_fraction)

self%ice_area_fraction%name = 'ice_area_fraction'
self%ice_area_fraction%units = '1'
self%ice_area_fraction%cf_names = 'sea_ice_area_fraction'
call add(self%ice_area_fraction)

self%mole_fraction_of_carbon_dioxide_in_air%name = 'mole_fraction_of_carbon_dioxide_in_air'
self%mole_fraction_of_carbon_dioxide_in_air%units = '1e-6'
self%mole_fraction_of_carbon_dioxide_in_air%cf_names = 'mole_fraction_of_carbon_dioxide_in_air'
call add(self%mole_fraction_of_carbon_dioxide_in_air)

self%surface_air_pressure%name = 'surface_air_pressure'
self%surface_air_pressure%units = 'Pa'
self%surface_air_pressure%cf_names = 'surface_air_pressure'
call add(self%surface_air_pressure)

self%surface_albedo%name = 'surface_albedo'
self%surface_albedo%units = '1'
self%surface_albedo%cf_names = 'surface_albedo'
self%surface_albedo%aggregate_variable = .true.
call add(self%surface_albedo)

self%surface_downwelling_photosynthetic_radiative_flux%name = 'surface_downwelling_photosynthetic_radiative_flux'
self%surface_downwelling_photosynthetic_radiative_flux%units = 'W m-2'
self%surface_downwelling_photosynthetic_radiative_flux%cf_names = 'surface_downwelling_photosynthetic_radiative_flux_in_sea_water'
call add(self%surface_downwelling_photosynthetic_radiative_flux)

self%surface_downwelling_photosynthetic_radiative_flux_in_air%name = 'surface_downwelling_photosynthetic_radiative_flux_in_air'
self%surface_downwelling_photosynthetic_radiative_flux_in_air%units = 'W m-2'
self%surface_downwelling_photosynthetic_radiative_flux_in_air%cf_names = 'surface_downwelling_photosynthetic_radiative_flux_in_air'
call add(self%surface_downwelling_photosynthetic_radiative_flux_in_air)

self%surface_downwelling_shortwave_flux%name = 'surface_downwelling_shortwave_flux'
self%surface_downwelling_shortwave_flux%units = 'W m-2'
call add(self%surface_downwelling_shortwave_flux)

self%surface_downwelling_shortwave_flux_in_air%name = 'surface_downwelling_shortwave_flux_in_air'
self%surface_downwelling_shortwave_flux_in_air%units = 'W m-2'
self%surface_downwelling_shortwave_flux_in_air%cf_names = 'surface_downwelling_shortwave_flux_in_air,surface_downwelling_shortwave_flux'
call add(self%surface_downwelling_shortwave_flux_in_air)

self%surface_drag_coefficient_in_air%name = 'surface_drag_coefficient_in_air'
self%surface_drag_coefficient_in_air%units = '1'
self%surface_drag_coefficient_in_air%cf_names = 'surface_drag_coefficient_in_air,atmosphere_surface_drag_coefficient'
self%surface_drag_coefficient_in_air%aggregate_variable = .true.
call add(self%surface_drag_coefficient_in_air)

self%surface_specific_humidity%name = 'surface_specific_humidity'
self%surface_specific_humidity%units = '1'
self%surface_specific_humidity%cf_names = 'surface_specific_humidity'
call add(self%surface_specific_humidity)

self%surface_temperature%name = 'surface_temperature'
self%surface_temperature%units = 'degree_Celsius'
self%surface_temperature%cf_names = 'sea_surface_temperature,surface_temperature,surface_temperature_where_land,surface_temperature_where_open_sea,surface_temperature_where_snow'
call add(self%surface_temperature)

self%wind_speed%name = 'wind_speed'
self%wind_speed%units = 'm s-1'
self%wind_speed%cf_names = 'wind_speed'
call add(self%wind_speed)

self%latitude%name = 'latitude'
self%latitude%units = 'degree_north'
self%latitude%cf_names = 'latitude'
call add(self%latitude)

self%longitude%name = 'longitude'
self%longitude%units = 'degree_east'
self%longitude%cf_names = 'longitude'
call add(self%longitude)

self%calendar_year%name = 'calendar_year'
self%calendar_year%units = 'year'
call add(self%calendar_year)

self%maximum_time_step%name = 'maximum_time_step'
self%maximum_time_step%units = 's'
call add(self%maximum_time_step)

self%number_of_days_in_year%name = 'number_of_days_in_year'
self%number_of_days_in_year%units = 'd'
call add(self%number_of_days_in_year)

self%number_of_days_since_start_of_the_year%name = 'number_of_days_since_start_of_the_year'
self%number_of_days_since_start_of_the_year%units = 'd'
call add(self%number_of_days_since_start_of_the_year)

self%total_carbon%name = 'total_carbon'
self%total_carbon%units = 'mmol m-3'
self%total_carbon%aggregate_variable = .true.
self%total_carbon%conserved = .true.
call add(self%total_carbon)

self%total_iron%name = 'total_iron'
self%total_iron%units = 'umol m-3'
self%total_iron%aggregate_variable = .true.
self%total_iron%conserved = .true.
call add(self%total_iron)

self%total_nitrogen%name = 'total_nitrogen'
self%total_nitrogen%units = 'mmol m-3'
self%total_nitrogen%aggregate_variable = .true.
self%total_nitrogen%conserved = .true.
call add(self%total_nitrogen)

self%total_phosphorus%name = 'total_phosphorus'
self%total_phosphorus%units = 'mmol m-3'
self%total_phosphorus%aggregate_variable = .true.
self%total_phosphorus%conserved = .true.
call add(self%total_phosphorus)

self%total_silicate%name = 'total_silicate'
self%total_silicate%units = 'mmol m-3'
self%total_silicate%aggregate_variable = .true.
self%total_silicate%conserved = .true.
call add(self%total_silicate)

