! DO NOT EDIT THIS FILE.
! It is automatically generated by ..\util\standard_variables\parse_standard_variables.py from ..\util\standard_variables\variables.yaml.
! Edit variables.yaml instead and re-run parse_standard_variables.py.
standard_variables%alkalinity_expressed_as_mole_equivalent%name = 'alkalinity_expressed_as_mole_equivalent'
standard_variables%alkalinity_expressed_as_mole_equivalent%units = 'mmol m-3'
standard_variables%alkalinity_expressed_as_mole_equivalent%cf_names = 'sea_water_alkalinity_expressed_as_mole_equivalent'
call add(standard_variables%alkalinity_expressed_as_mole_equivalent)

standard_variables%attenuation_coefficient_of_photosynthetic_radiative_flux%name = 'attenuation_coefficient_of_photosynthetic_radiative_flux'
standard_variables%attenuation_coefficient_of_photosynthetic_radiative_flux%units = 'm-1'
standard_variables%attenuation_coefficient_of_photosynthetic_radiative_flux%aggregate_variable = .true.
call add(standard_variables%attenuation_coefficient_of_photosynthetic_radiative_flux)

standard_variables%attenuation_coefficient_of_shortwave_flux%name = 'attenuation_coefficient_of_shortwave_flux'
standard_variables%attenuation_coefficient_of_shortwave_flux%units = 'm-1'
standard_variables%attenuation_coefficient_of_shortwave_flux%aggregate_variable = .true.
call add(standard_variables%attenuation_coefficient_of_shortwave_flux)

standard_variables%cell_thickness%name = 'cell_thickness'
standard_variables%cell_thickness%units = 'm'
standard_variables%cell_thickness%cf_names = 'cell_thickness'
call add(standard_variables%cell_thickness)

standard_variables%density%name = 'density'
standard_variables%density%units = 'kg m-3'
standard_variables%density%cf_names = 'sea_water_density'
call add(standard_variables%density)

standard_variables%depth%name = 'depth'
standard_variables%depth%units = 'm'
standard_variables%depth%cf_names = 'depth'
call add(standard_variables%depth)

standard_variables%downwelling_photosynthetic_radiative_flux%name = 'downwelling_photosynthetic_radiative_flux'
standard_variables%downwelling_photosynthetic_radiative_flux%units = 'W m-2'
standard_variables%downwelling_photosynthetic_radiative_flux%cf_names = 'downwelling_photosynthetic_radiative_flux_in_sea_water'
call add(standard_variables%downwelling_photosynthetic_radiative_flux)

standard_variables%downwelling_shortwave_flux%name = 'downwelling_shortwave_flux'
standard_variables%downwelling_shortwave_flux%units = 'W m-2'
standard_variables%downwelling_shortwave_flux%cf_names = 'downwelling_shortwave_flux_in_sea_water'
call add(standard_variables%downwelling_shortwave_flux)

standard_variables%fractional_saturation_of_oxygen%name = 'fractional_saturation_of_oxygen'
standard_variables%fractional_saturation_of_oxygen%units = '1'
standard_variables%fractional_saturation_of_oxygen%cf_names = 'fractional_saturation_of_oxygen_in_sea_water'
call add(standard_variables%fractional_saturation_of_oxygen)

standard_variables%mass_concentration_of_suspended_matter%name = 'mass_concentration_of_suspended_matter'
standard_variables%mass_concentration_of_suspended_matter%units = 'g m-3'
standard_variables%mass_concentration_of_suspended_matter%cf_names = 'mass_concentration_of_suspended_matter_in_sea_water,concentration_of_suspended_matter_in_sea_water'
call add(standard_variables%mass_concentration_of_suspended_matter)

standard_variables%mole_concentration_of_ammonium%name = 'mole_concentration_of_ammonium'
standard_variables%mole_concentration_of_ammonium%units = 'mmol m-3'
standard_variables%mole_concentration_of_ammonium%cf_names = 'mole_concentration_of_ammonium_in_sea_water'
call add(standard_variables%mole_concentration_of_ammonium)

standard_variables%mole_concentration_of_carbonate_expressed_as_carbon%name = 'mole_concentration_of_carbonate_expressed_as_carbon'
standard_variables%mole_concentration_of_carbonate_expressed_as_carbon%units = 'mmol m-3'
standard_variables%mole_concentration_of_carbonate_expressed_as_carbon%cf_names = 'mole_concentration_of_carbonate_expressed_as_carbon_in_sea_water'
call add(standard_variables%mole_concentration_of_carbonate_expressed_as_carbon)

standard_variables%mole_concentration_of_dissolved_inorganic_carbon%name = 'mole_concentration_of_dissolved_inorganic_carbon'
standard_variables%mole_concentration_of_dissolved_inorganic_carbon%units = 'mmol m-3'
standard_variables%mole_concentration_of_dissolved_inorganic_carbon%cf_names = 'mole_concentration_of_dissolved_inorganic_carbon_in_sea_water'
call add(standard_variables%mole_concentration_of_dissolved_inorganic_carbon)

standard_variables%mole_concentration_of_dissolved_iron%name = 'mole_concentration_of_dissolved_iron'
standard_variables%mole_concentration_of_dissolved_iron%units = 'umol m-3'
standard_variables%mole_concentration_of_dissolved_iron%cf_names = 'mole_concentration_of_dissolved_iron_in_sea_water'
call add(standard_variables%mole_concentration_of_dissolved_iron)

standard_variables%mole_concentration_of_nitrate%name = 'mole_concentration_of_nitrate'
standard_variables%mole_concentration_of_nitrate%units = 'mmol m-3'
standard_variables%mole_concentration_of_nitrate%cf_names = 'mole_concentration_of_nitrate_in_sea_water'
call add(standard_variables%mole_concentration_of_nitrate)

standard_variables%mole_concentration_of_phosphate%name = 'mole_concentration_of_phosphate'
standard_variables%mole_concentration_of_phosphate%units = 'mmol m-3'
standard_variables%mole_concentration_of_phosphate%cf_names = 'mole_concentration_of_phosphate_in_sea_water'
call add(standard_variables%mole_concentration_of_phosphate)

standard_variables%mole_concentration_of_silicate%name = 'mole_concentration_of_silicate'
standard_variables%mole_concentration_of_silicate%units = 'mmol m-3'
standard_variables%mole_concentration_of_silicate%cf_names = 'mole_concentration_of_silicate_in_sea_water'
call add(standard_variables%mole_concentration_of_silicate)

standard_variables%net_rate_of_absorption_of_shortwave_energy_in_layer%name = 'net_rate_of_absorption_of_shortwave_energy_in_layer'
standard_variables%net_rate_of_absorption_of_shortwave_energy_in_layer%units = 'W m-2'
standard_variables%net_rate_of_absorption_of_shortwave_energy_in_layer%cf_names = 'net_rate_of_absorption_of_shortwave_energy_in_ocean_layer'
call add(standard_variables%net_rate_of_absorption_of_shortwave_energy_in_layer)

standard_variables%ph_reported_on_total_scale%name = 'ph_reported_on_total_scale'
standard_variables%ph_reported_on_total_scale%units = '1'
standard_variables%ph_reported_on_total_scale%cf_names = 'sea_water_ph_reported_on_total_scale'
call add(standard_variables%ph_reported_on_total_scale)

standard_variables%practical_salinity%name = 'practical_salinity'
standard_variables%practical_salinity%units = '1e-3'
standard_variables%practical_salinity%cf_names = 'sea_water_practical_salinity'
call add(standard_variables%practical_salinity)

standard_variables%pressure%name = 'pressure'
standard_variables%pressure%units = 'dbar'
standard_variables%pressure%cf_names = 'sea_water_pressure'
call add(standard_variables%pressure)

standard_variables%secchi_depth%name = 'secchi_depth'
standard_variables%secchi_depth%units = 'm'
standard_variables%secchi_depth%cf_names = 'secchi_depth_of_sea_water'
call add(standard_variables%secchi_depth)

standard_variables%temperature%name = 'temperature'
standard_variables%temperature%units = 'degree_Celsius'
standard_variables%temperature%cf_names = 'sea_water_temperature'
call add(standard_variables%temperature)

standard_variables%bottom_depth%name = 'bottom_depth'
standard_variables%bottom_depth%units = 'm'
call add(standard_variables%bottom_depth)

standard_variables%bottom_depth_below_geoid%name = 'bottom_depth_below_geoid'
standard_variables%bottom_depth_below_geoid%units = 'm'
standard_variables%bottom_depth_below_geoid%cf_names = 'sea_floor_depth_below_geoid,sea_floor_depth'
call add(standard_variables%bottom_depth_below_geoid)

standard_variables%bottom_roughness_length%name = 'bottom_roughness_length'
standard_variables%bottom_roughness_length%units = 'm'
call add(standard_variables%bottom_roughness_length)

standard_variables%bottom_stress%name = 'bottom_stress'
standard_variables%bottom_stress%units = 'Pa'
call add(standard_variables%bottom_stress)

standard_variables%cloud_area_fraction%name = 'cloud_area_fraction'
standard_variables%cloud_area_fraction%units = '1'
standard_variables%cloud_area_fraction%cf_names = 'cloud_area_fraction'
call add(standard_variables%cloud_area_fraction)

standard_variables%ice_area_fraction%name = 'ice_area_fraction'
standard_variables%ice_area_fraction%units = '1'
standard_variables%ice_area_fraction%cf_names = 'sea_ice_area_fraction'
call add(standard_variables%ice_area_fraction)

standard_variables%mole_fraction_of_carbon_dioxide_in_air%name = 'mole_fraction_of_carbon_dioxide_in_air'
standard_variables%mole_fraction_of_carbon_dioxide_in_air%units = '1e-6'
standard_variables%mole_fraction_of_carbon_dioxide_in_air%cf_names = 'mole_fraction_of_carbon_dioxide_in_air'
call add(standard_variables%mole_fraction_of_carbon_dioxide_in_air)

standard_variables%surface_air_pressure%name = 'surface_air_pressure'
standard_variables%surface_air_pressure%units = 'Pa'
standard_variables%surface_air_pressure%cf_names = 'surface_air_pressure'
call add(standard_variables%surface_air_pressure)

standard_variables%surface_albedo%name = 'surface_albedo'
standard_variables%surface_albedo%units = '1'
standard_variables%surface_albedo%cf_names = 'surface_albedo'
standard_variables%surface_albedo%aggregate_variable = .true.
call add(standard_variables%surface_albedo)

standard_variables%surface_downwelling_photosynthetic_radiative_flux%name = 'surface_downwelling_photosynthetic_radiative_flux'
standard_variables%surface_downwelling_photosynthetic_radiative_flux%units = 'W m-2'
standard_variables%surface_downwelling_photosynthetic_radiative_flux%cf_names = 'surface_downwelling_photosynthetic_radiative_flux_in_sea_water'
call add(standard_variables%surface_downwelling_photosynthetic_radiative_flux)

standard_variables%surface_downwelling_photosynthetic_radiative_flux_in_air%name = 'surface_downwelling_photosynthetic_radiative_flux_in_air'
standard_variables%surface_downwelling_photosynthetic_radiative_flux_in_air%units = 'W m-2'
standard_variables%surface_downwelling_photosynthetic_radiative_flux_in_air%cf_names = 'surface_downwelling_photosynthetic_radiative_flux_in_air'
call add(standard_variables%surface_downwelling_photosynthetic_radiative_flux_in_air)

standard_variables%surface_downwelling_shortwave_flux%name = 'surface_downwelling_shortwave_flux'
standard_variables%surface_downwelling_shortwave_flux%units = 'W m-2'
call add(standard_variables%surface_downwelling_shortwave_flux)

standard_variables%surface_downwelling_shortwave_flux_in_air%name = 'surface_downwelling_shortwave_flux_in_air'
standard_variables%surface_downwelling_shortwave_flux_in_air%units = 'W m-2'
standard_variables%surface_downwelling_shortwave_flux_in_air%cf_names = 'surface_downwelling_shortwave_flux_in_air,surface_downwelling_shortwave_flux'
call add(standard_variables%surface_downwelling_shortwave_flux_in_air)

standard_variables%surface_drag_coefficient_in_air%name = 'surface_drag_coefficient_in_air'
standard_variables%surface_drag_coefficient_in_air%units = '1'
standard_variables%surface_drag_coefficient_in_air%cf_names = 'surface_drag_coefficient_in_air,atmosphere_surface_drag_coefficient'
standard_variables%surface_drag_coefficient_in_air%aggregate_variable = .true.
call add(standard_variables%surface_drag_coefficient_in_air)

standard_variables%surface_specific_humidity%name = 'surface_specific_humidity'
standard_variables%surface_specific_humidity%units = '1'
standard_variables%surface_specific_humidity%cf_names = 'surface_specific_humidity'
call add(standard_variables%surface_specific_humidity)

standard_variables%surface_temperature%name = 'surface_temperature'
standard_variables%surface_temperature%units = 'degree_Celsius'
standard_variables%surface_temperature%cf_names = 'sea_surface_temperature,surface_temperature,surface_temperature_where_land,surface_temperature_where_open_sea,surface_temperature_where_snow'
call add(standard_variables%surface_temperature)

standard_variables%wind_speed%name = 'wind_speed'
standard_variables%wind_speed%units = 'm s-1'
standard_variables%wind_speed%cf_names = 'wind_speed'
call add(standard_variables%wind_speed)

standard_variables%latitude%name = 'latitude'
standard_variables%latitude%units = 'degree_north'
standard_variables%latitude%cf_names = 'latitude'
call add(standard_variables%latitude)

standard_variables%longitude%name = 'longitude'
standard_variables%longitude%units = 'degree_east'
standard_variables%longitude%cf_names = 'longitude'
call add(standard_variables%longitude)

standard_variables%number_of_days_since_start_of_the_year%name = 'number_of_days_since_start_of_the_year'
standard_variables%number_of_days_since_start_of_the_year%units = 'd'
call add(standard_variables%number_of_days_since_start_of_the_year)

standard_variables%total_carbon%name = 'total_carbon'
standard_variables%total_carbon%units = 'mmol m-3'
standard_variables%total_carbon%aggregate_variable = .true.
standard_variables%total_carbon%conserved = .true.
call add(standard_variables%total_carbon)

standard_variables%total_iron%name = 'total_iron'
standard_variables%total_iron%units = 'umol m-3'
standard_variables%total_iron%aggregate_variable = .true.
standard_variables%total_iron%conserved = .true.
call add(standard_variables%total_iron)

standard_variables%total_nitrogen%name = 'total_nitrogen'
standard_variables%total_nitrogen%units = 'mmol m-3'
standard_variables%total_nitrogen%aggregate_variable = .true.
standard_variables%total_nitrogen%conserved = .true.
call add(standard_variables%total_nitrogen)

standard_variables%total_phosphorus%name = 'total_phosphorus'
standard_variables%total_phosphorus%units = 'mmol m-3'
standard_variables%total_phosphorus%aggregate_variable = .true.
standard_variables%total_phosphorus%conserved = .true.
call add(standard_variables%total_phosphorus)

standard_variables%total_silicate%name = 'total_silicate'
standard_variables%total_silicate%units = 'mmol m-3'
standard_variables%total_silicate%aggregate_variable = .true.
standard_variables%total_silicate%conserved = .true.
call add(standard_variables%total_silicate)

